version: '3.1'

services:

  ghost2:
    image: ghost:3.42-alpine
    restart: always
    ports:
      - 8030:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db3
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:8030
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development

  db3:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_ROOT_PASSWORD: ghost